### ISSUE TITLE
Jupyter container is crashing

### ISSUE THREAD

**Issue by znmeb** [hackoregon/data-science-pet-containers#17]
To reproduce:

```
$ docker-compose -f medium.yml up -d
Creating network "containers_default" with the default driver
Creating containers_jupyter_1 ... done
Creating containers_postgis_1 ... done
$ docker logs containers_jupyter_1 
Traceback (most recent call last):
  File "/home/jupyter/.conda/envs/jupyter/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/jupyter/.conda/envs/jupyter/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/home/jupyter/.conda/envs/jupyter/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

This looks like it's upstream. I've been meaning to refactor this anyway. Since none of the containers depend on each other anyhow, it makes sense to create a compose file for each rather than "small", "medium" and "large". `docker-compose up` does the right thing by default.

That won't fix this bug, but adding an Anacoda image / container / compose file will - if Jupyter crashes in the Anaconda container it's obviously upstream.

**Comment by znmeb** [comment]
OK - the Anaconda folks know what the problem is - https://github.com/ContinuumIO/anaconda-issues/issues/8789

Looks like I found it the same time they did - it turns out that an upgrade to `tornado` from 4.5.3 to 5.0 breaks a bunch o' stuff.

**Comment by znmeb** [comment]
Fix is to use the Anaconda Docker image and don't update it!
